* beancounter-cron

This is a subsystem inteded to work with beancount to automatically add
standing orders to your beancount file. 

** Why?

To avoid having to enter monthly payments over and over again

** Basic format

** Designators

| Designator | Explanation                                                                                  |
|------------+----------------------------------------------------------------------------------------------|
| daily      | every day                                                                                    |
| weekly     | every week on that workday                                                                   |
| monthly    | every calendar month on that day (if the day does not exist, use the day immediately before) |
| yearly     | every calendar year on that day (if the day does not exist, use the day immediately before)  |

You can modify this by adding a digit (e.g. 4daily = every four days)

* License

Copyright (C) 2018 Martin Hohenberg <me@martinhohenberg.de>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
